import { test,after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fixture,testGuard } from '../fixture';
import { rows,execute,closePool } from '../../src/server/db';
import { importPersonnelSeed } from '../../src/server/personnel-seed';
import { enrollMany } from '../../src/server/registry';
import { publicCalendar } from '../../src/server/public-calendar';
testGuard();after(closePool);
test('personnel seed is atomic, repeatable, preserves later edits and supports bulk roster',async()=>{
  const f=await fixture(),tag=randomUUID().slice(0,8);
  const people=[1,2].map(i=>({employeeCode:`SEED-${tag}-${i}`,prefix:'',firstName:`ทดสอบนำเข้า${tag}${i}`,lastName:'สมมติ',position:`ตำแหน่ง ${tag}`,level:'ระดับทดสอบ',group:`กลุ่มงาน ${tag}`,department:`หน่วยงาน ${tag}`,employmentType:'ทดสอบ',active:true,sourceRow:i+2}));
  const seed={version:1,source:'synthetic.xlsx',snapshotDate:f.day,people};
  const result=await importPersonnelSeed(seed,f.actor.id);assert.equal(result.created,2);
  const saved=await rows<{id:number;department_id:number;group_name:string}>('SELECT e.id,a.department_id,g.name group_name FROM employees e JOIN employee_assignments a ON a.employee_id=e.id JOIN departments d ON d.id=a.department_id JOIN departments g ON g.id=d.parent_id WHERE e.employee_code IN (?,?)',people.map(p=>p.employeeCode));
  assert.equal(saved.length,2);assert.equal(saved[0].group_name,people[0].group);
  await execute('UPDATE employees SET active=0 WHERE id=?',[saved[0].id]);
  const replay=await importPersonnelSeed(seed,f.actor.id);assert.equal(replay.created,0);assert.equal(replay.unchanged,2);
  assert.equal((await rows<{active:number}>('SELECT active FROM employees WHERE id=?',[saved[0].id]))[0].active,0);
  const conflict={...seed,people:[{...people[0],employeeCode:`NEW-${tag}`,firstName:`บุคคลใหม่${tag}`},{...people[1],employeeCode:`DIFF-${tag}`} ]};
  await assert.rejects(importPersonnelSeed(conflict,f.actor.id),/รหัสต่างกัน/);
  assert.equal((await rows('SELECT id FROM employees WHERE employee_code=?',[`NEW-${tag}`])).length,0);
  await execute('UPDATE employees SET active=1 WHERE id=?',[saved[0].id]);
  const roster={planId:f.planId,snapshotDate:f.day,serviceIds:[f.serviceId],rounds:1};
  await assert.rejects(enrollMany({...roster,employeeIds:[saved[0].id,999999999]},f.actor));
  assert.equal((await rows('SELECT id FROM fiscal_year_members WHERE employee_id=?',[saved[0].id])).length,0);
  assert.equal((await enrollMany({...roster,employeeIds:saved.map(p=>p.id)},f.actor)).enrolled,2);
  await enrollMany({...roster,employeeIds:saved.map(p=>p.id)},f.actor);
  assert.equal((await rows('SELECT id FROM fiscal_year_members WHERE employee_id IN (?,?)',saved.map(p=>p.id))).length,2);
  const calendar=await publicCalendar(new URLSearchParams({year:String(f.yearId),month:f.day.slice(0,7)}));
  const text=JSON.stringify(calendar);assert.ok(!text.includes('first_name'));assert.ok(!text.includes('display_name'));assert.ok(!text.includes('identity_snapshot'));assert.ok(!text.includes('employee_code'));
  await assert.rejects(publicCalendar(new URLSearchParams({year:String(f.yearId),month:'2027-13'})));
});
