'use client';
import { AnnualPlan } from './annual-plan';
import { useState } from 'react';
import { Download,Upload,CheckCircle2 } from 'lucide-react';
import { Table,s,n,thaiDate,type Item,type Api } from './ui';
import type { Masters } from './schedule';
type Preview={batchId:string;digest:string;total:number;valid:number;invalid:number;errors:{row:number;field:string;message:string}[];preview:{sourceRow:number;action:string;input:{memberId:number;date:string;time:string;roundNo:number;serviceIds:number[]}}[]};
export function Imports({year,masters,members,api,csrf,reload,history}:{year:Item;masters:Masters;members:Item[];api:Api;csrf:string;reload:()=>void;history:Item[]}){
 const plans=(masters.plans??[]).filter(p=>n(p.fiscal_year_id)===year.id),[plan,setPlan]=useState(s(plans[0]?.id)),[preview,setPreview]=useState<Preview>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');
 return <><div className="section-head"><div><h2>นำเข้านัดหมายจาก Excel</h2><p className="muted">ตรวจสอบทุกแถวก่อนบันทึก · สูงสุด 10,000 แถว / 10 MB</p></div></div><div className="import-steps"><span><b>1</b>โหลดแม่แบบของปีนี้</span><span><b>2</b>กรอกและตรวจสอบไฟล์</span><span><b>3</b>ตรวจทานแล้วยืนยัน</span></div><section className="surface padded"><div className="import-choice"><AnnualPlan plans={plans} value={plan} onChange={value=>{setPlan(value);setPreview(undefined);setDone('');}}/>{plan&&<a className="button" href={`/api/v1/imports/template?year=${year.id}&plan=${plan}`}><Download size={18}/>ดาวน์โหลดแม่แบบ .xlsx</a>}</div><p className="helper">แม่แบบมีรหัสบุคลากร รายการตรวจ และสิทธิ์รายคนของปีนี้ วันที่ในไฟล์ใช้ ค.ศ. YYYY-MM-DD · CREATE สำหรับนัดใหม่ และ UPDATE พร้อมรหัสนัดและ version สำหรับแก้ไข</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set('year',String(year.id));f.set('plan',plan);setBusy(true);setError('');setDone('');setPreview(undefined);try{const r=await fetch('/api/v1/imports/validate',{method:'POST',headers:{'x-csrf-token':csrf},body:f});const b=await r.json();if(!r.ok)throw Error(b.message);setPreview(b);}catch(e){setError(e instanceof Error?e.message:'อ่านไฟล์ไม่ได้');}finally{setBusy(false);}}}><label className="upload"><Upload size={26}/><span>เลือกไฟล์ Excel ที่กรอกจากแม่แบบ</span><input name="file" type="file" accept=".xlsx" required disabled={!plan||busy}/><small>ไม่รับสูตร มาโคร หรือลิงก์ภายนอก</small></label><button className="primary" disabled={busy||!plan}>{busy?'กำลังตรวจสอบ…':'ตรวจสอบข้อมูล'}</button></form></section>{error&&<p role="alert" className="error">{error}</p>}{done&&<div role="status" className="success"><CheckCircle2 size={20}/>{done}</div>}
 {preview&&<section className="surface padded"><div className="section-head"><div><h3>ผลการตรวจสอบ</h3><p>{preview.total} แถว · ผ่าน {preview.valid} · ต้องแก้ไข {preview.invalid}</p></div><button className="primary" disabled={busy||!!preview.invalid||!preview.valid||!!done} onClick={async()=>{setBusy(true);setError('');try{const r=await api(`imports/${preview.batchId}/confirm`,'POST',{digest:preview.digest}) as {success:number};setDone(`บันทึกสำเร็จ ${r.success} นัดหมาย`);reload();}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}}>{busy?'กำลังบันทึก…':'ยืนยันนำเข้าทั้งชุด'}</button></div>{!!preview.invalid&&<><p className="error">ยังไม่บันทึกนัดใด ๆ กรุณาแก้ไขไฟล์และตรวจสอบใหม่ให้ผ่านทุกแถว</p><Table headers={['แถวใน Excel','รายละเอียด']}>{preview.errors.map((e,i)=><tr key={i}><td>{e.row}</td><td>{e.message}</td></tr>)}</Table></>}<Table headers={['แถว','การทำงาน','บุคลากร','วัน–เวลา','รายการตรวจ / รอบ']} empty={!preview.preview.length}>{preview.preview.map(p=><tr key={p.sourceRow}><td>{p.sourceRow}</td><td>{p.action==='CREATE'?'เพิ่มนัดใหม่':'แก้ไขนัดเดิม'}</td><td>{s(members.find(m=>m.id===p.input.memberId)?.display_name)}</td><td>{thaiDate(p.input.date)} · {p.input.time}</td><td>{p.input.serviceIds.map(id=>s(masters.services?.find(x=>x.id===id)?.name)).join(', ')} · รอบ {p.input.roundNo}</td></tr>)}</Table><p className="helper">ผลตรวจสอบใช้ได้ 24 ชั่วโมง ระบบตรวจซ้ำเมื่อยืนยัน หากมีรายการขัดแย้งจะยกเลิกทั้งชุด</p></section>}<section className="surface padded"><h3>ประวัติการนำเข้าของคุณ</h3><Table headers={["ไฟล์","สถานะ","ทั้งหมด / ผ่าน / ผิด","บันทึกสำเร็จ"]} empty={!history.length}>{history.map(h=><tr key={s(h.id)}><td>{s(h.filename)}<small>{s(h.created_at)} UTC</small></td><td>{s(h.status)}</td><td>{n(h.total_rows)} / {n(h.valid_rows)} / {n(h.invalid_rows)}</td><td>{n(h.success_rows)} แถว</td></tr>)}</Table></section></>;
}
