'use client';
import { NotificationTest } from './notification-test';
import { NoticePreview } from './notice-preview';
import { ReminderRounds } from './reminder-rounds';
import { useState } from 'react';
import { Field,FormPanel,Table,s,n,thaiDate,type Item,type Api } from './ui';
export function Notifications({jobs,settings,employees,api,reload}:{jobs:Item[];settings:Item;employees:Item[];api:Api;reload:()=>void}){
 const [editing,setEditing]=useState(false),[retry,setRetry]=useState<Item>();
 const names:Record<string,string>={PENDING:'รอส่ง',SENDING:'กำลังส่ง',ACCEPTED:'MOPH รับคำขอแล้ว',FAILED:'ส่งไม่ผ่าน',UNKNOWN:'ยังยืนยันผลไม่ได้',CANCELLED:'ยกเลิก',BLOCKED:'ข้อมูลผู้รับไม่พร้อม',DRY_RUN:'ทดสอบ ไม่ได้ส่งจริง'};
 return <><div className="section-head"><div><h2>แจ้งเตือนผ่าน MOPH Alert</h2><p className="muted">แจ้งนัดจาก HOSxP ผ่าน LINE หมอพร้อมให้บุคลากรในทะเบียนเดิม</p></div><button onClick={()=>setEditing(true)}>ตั้งค่าการแจ้งเตือน</button></div><div className="notice"><strong>{settings.enabled?(settings.mode==='LIVE'?'เปิดส่งจริง':'โหมดทดสอบ · ไม่ส่งข้อความ'):'ปิดการแจ้งเตือน'}</strong><span>แจ้งทันทีเมื่อลงนัดหรือเลื่อนนัดใน HOSxP · แจ้งซ้ำก่อนวันนัด {(settings.rules as Item[]|undefined)?.filter(r=>r.active).map(r=>n(r.days_before)).join(', ')||'—'} วัน · กดส่งเองได้</span></div><p className="helper">“MOPH รับคำขอแล้ว” ไม่ได้ยืนยันว่าผู้รับอ่านหรือได้รับข้อความ หากผลไม่ชัดเจน ระบบจะไม่ส่งซ้ำอัตโนมัติ</p>
 {editing&&<FormPanel title="ตั้งค่าการแจ้งเตือน" onClose={()=>setEditing(false)} onSubmit={async f=>{await api('notification-settings','PATCH',{enabled:f.get('enabled')==='on',mode:f.get('mode'),version:settings.version,days:[...new Set(f.getAll('days').map(Number).filter(d=>Number.isInteger(d)&&d>=0&&d<=30))],confirmLive:f.get('confirmLive')==='on',showBrand:f.get('showBrand')==='on'});reload();}}><label className="checkbox"><input name="enabled" type="checkbox" defaultChecked={!!settings.enabled}/>เปิดใช้ worker แจ้งเตือน</label><label>โหมด<select name="mode" defaultValue={s(settings.mode)}><option value="DRY_RUN">ทดสอบ (ไม่ส่งจริง)</option><option value="LIVE">ส่งจริง</option></select></label><label className="checkbox span-all"><input name="showBrand" type="checkbox" defaultChecked={settings.show_brand==null||!!settings.show_brand}/>แสดงโลโก้และชื่อโรงพยาบาลบนหัวการ์ด LINE</label><ReminderRounds rules={(settings.rules as Item[]|undefined)??[]}/><label className="checkbox"><input type="checkbox" name="confirmLive"/>ยืนยันเปิดส่งจริงไปยังผู้รับที่ตรวจสอบแล้ว</label><p className="helper span-all">สถานะ server: {settings.credentialConfigured?'ตั้งค่า Client_ID และ Secret แล้ว':'ยังไม่ได้ตั้ง Client_ID และ Secret'} · {settings.serverLiveEnabled?'อนุญาตส่งจริง':'ยังไม่อนุญาตส่งจริง'} ใส่ Client_ID ใน MOPH_CLIENT_KEY และ Secret ใน MOPH_SECRET_KEY ของ .env แล้ว restart app/worker; Free Form เว้น MOPH_BEARER_TOKEN ว่างได้</p></FormPanel>}
 <p className="helper">สถานะอ่าน HOSxP: {(settings.hosxp as Item)?.initialized?'เริ่มรับนัดแล้ว':'รอ worker อ่านข้อมูลตั้งต้น'} · อ่านล่าสุด (UTC): {s((settings.hosxp as Item)?.last_success_at)||'—'}</p>
 <NoticePreview showBrand={settings.show_brand==null||!!settings.show_brand}/>
 <NotificationTest employees={employees} settings={settings} api={api}/>
 {retry&&<FormPanel title="ตรวจสอบก่อนส่งซ้ำ" onClose={()=>setRetry(undefined)} onSubmit={async f=>{await api(`notifications/${retry.id}/retry`,'POST',{reason:f.get('reason'),acknowledgeUnknown:f.get('ack')==='on'});reload();}}><p className="span-all">{s(retry.display_name)} · {thaiDate(retry.appointment_date)} · {names[s(retry.status)]}</p><Field label="เหตุผลที่ส่งซ้ำ / ผลตรวจสอบ" name="reason" required/>{retry.status==='UNKNOWN'&&<label className="checkbox"><input type="checkbox" name="ack" required/>ตรวจสอบกับผู้ให้บริการแล้ว และยอมรับความเสี่ยงข้อความซ้ำ</label>}</FormPanel>}
 <div className="surface"><Table headers={['บุคลากร / นัดหมาย','ประเภท','สถานะ','รายละเอียด','จัดการ']} empty={!jobs.length}>{jobs.map(j=><tr key={s(j.id)}><td><strong>{s(j.display_name)}</strong><small>{thaiDate(j.appointment_date)} · {s(j.appointment_time).slice(0,5)}</small></td><td>{j.hosxp_oapp_id?({NEW:'ลงนัด / เลื่อนนัด',REMINDER:`ก่อนวันนัด ${n(j.days_before)} วัน`,MANUAL:'กดส่งเอง',CANCELLED:'ยกเลิกนัด'} as Record<string,string>)[s(j.kind)]??'นัดจาก HOSxP':`ประวัติเดิม · ${n(j.days_before)} วัน`}</td><td><span className="badge">{names[s(j.status)]??s(j.status)}</span></td><td>{s(j.safe_error)||'—'}<small>พยายามส่ง {n(j.attempt_count)} ครั้ง</small></td><td>{!!j.hosxp_oapp_id&&['FAILED','BLOCKED','UNKNOWN','DRY_RUN'].includes(s(j.status))&&n(j.attempt_count)<3&&<button onClick={()=>setRetry(j)}>ตรวจสอบ / ส่งซ้ำ</button>}</td></tr>)}</Table></div></>;
}
