'use client';
import { useState } from 'react';
import { Field,FormPanel,Table,s,n,thaiDate,type Item,type Api } from './ui';
export function Notifications({jobs,settings,api,reload}:{jobs:Item[];settings:Item;api:Api;reload:()=>void}){
 const [editing,setEditing]=useState(false),[retry,setRetry]=useState<Item>();
 const rules=(settings.rules??[]) as Item[];const names:Record<string,string>={PENDING:'รอส่ง',SENDING:'กำลังส่ง',ACCEPTED:'MOPH รับคำขอแล้ว',FAILED:'ส่งไม่ผ่าน',UNKNOWN:'ยังยืนยันผลไม่ได้',CANCELLED:'ยกเลิก',BLOCKED:'ข้อมูลผู้รับไม่พร้อม',DRY_RUN:'ทดสอบ ไม่ได้ส่งจริง'};
 return <><div className="section-head"><div><h2>แจ้งเตือนผ่าน MOPH Alert</h2><p className="muted">ติดตามคำขอแจ้งนัดไปยัง LINE OA ที่เชื่อมกับ MOPH Alert</p></div><button onClick={()=>setEditing(true)}>ตั้งค่าการแจ้งเตือน</button></div><div className="notice"><strong>{settings.enabled?(settings.mode==='LIVE'?'เปิดส่งจริง':'โหมดทดสอบ · ไม่ส่งข้อความ'):'ปิดการแจ้งเตือน'}</strong><span>เตือนล่วงหน้า {rules.filter(r=>r.active).map(r=>s(r.days_before)).join(', ')||'—'} วัน เวลา {s(settings.send_local_time).slice(0,5)} น.</span></div><p className="helper">“MOPH รับคำขอแล้ว” ไม่ได้ยืนยันว่าผู้รับอ่านหรือได้รับข้อความ หากผลไม่ชัดเจน ระบบจะไม่ส่งซ้ำอัตโนมัติ</p>
 {editing&&<FormPanel title="ตั้งค่าการแจ้งเตือน" onClose={()=>setEditing(false)} onSubmit={async f=>{await api('notification-settings','PATCH',{enabled:f.get('enabled')==='on',mode:f.get('mode'),version:settings.version,days:s(f.get('days')).split(',').filter(v=>v.trim()).map(Number),confirmLive:f.get('confirmLive')==='on'});reload();}}><label className="checkbox"><input name="enabled" type="checkbox" defaultChecked={!!settings.enabled}/>เปิดใช้ worker แจ้งเตือน</label><label>โหมด<select name="mode" defaultValue={s(settings.mode)}><option value="DRY_RUN">ทดสอบ (ไม่ส่งจริง)</option><option value="LIVE">ส่งจริง</option></select></label><Field label="จำนวนวันล่วงหน้า คั่นด้วย ," name="days" defaultValue={rules.filter(r=>r.active).map(r=>s(r.days_before)).join(',')} placeholder="7,3,1"/><label className="checkbox"><input type="checkbox" name="confirmLive"/>ยืนยันเปิดส่งจริงไปยังผู้รับที่ตรวจสอบแล้ว</label><p className="helper span-all">สถานะ server: {settings.credentialConfigured?'ตั้งค่า credential แล้ว':'ยังไม่ได้ตั้ง credential'} · {settings.serverLiveEnabled?'อนุญาตส่งจริง':'ยังไม่อนุญาตส่งจริง'} ต้องตั้งค่าฝั่ง server และตรวจสอบผู้รับก่อนเปิด LIVE</p></FormPanel>}
 {retry&&<FormPanel title="ตรวจสอบก่อนส่งซ้ำ" onClose={()=>setRetry(undefined)} onSubmit={async f=>{await api(`notifications/${retry.id}/retry`,'POST',{reason:f.get('reason'),acknowledgeUnknown:f.get('ack')==='on'});reload();}}><p className="span-all">{s(retry.display_name)} · {thaiDate(retry.appointment_date)} · {names[s(retry.status)]}</p><Field label="เหตุผลที่ส่งซ้ำ / ผลตรวจสอบ" name="reason" required/>{retry.status==='UNKNOWN'&&<label className="checkbox"><input type="checkbox" name="ack" required/>ตรวจสอบกับผู้ให้บริการแล้ว และยอมรับความเสี่ยงข้อความซ้ำ</label>}</FormPanel>}
 <div className="surface"><Table headers={['บุคลากร / นัดหมาย','ล่วงหน้า','สถานะ','รายละเอียด','จัดการ']} empty={!jobs.length}>{jobs.map(j=><tr key={s(j.id)}><td><strong>{s(j.display_name)}</strong><small>{thaiDate(j.appointment_date)} · {s(j.appointment_time).slice(0,5)}</small></td><td>{n(j.days_before)} วัน</td><td><span className="badge">{names[s(j.status)]??s(j.status)}</span></td><td>{s(j.safe_error)||'—'}<small>พยายามส่ง {n(j.attempt_count)} ครั้ง</small></td><td>{['FAILED','BLOCKED','UNKNOWN','DRY_RUN'].includes(s(j.status))&&n(j.attempt_count)<3&&<button onClick={()=>setRetry(j)}>ตรวจสอบ / ส่งซ้ำ</button>}</td></tr>)}</Table></div></>;
}
