'use client';
import { useState } from 'react';
import { Select,s,type Item,type Api } from './ui';
import { TEST_NOTIFICATION_TEXT } from '@/src/domain/test-message';

type Result={id:string;status:string;safe_error:string|null;http_status:number|null;provider_code:string|null};
export function NotificationTest({employees,settings,api}:{employees:Item[];settings:Item;api:Api}){
  const [employee,setEmployee]=useState(''),[requestId,setRequestId]=useState(''),[result,setResult]=useState<Result>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const recipients=employees.filter(e=>e.active&&e.has_cid&&e.notification_enabled).map(e=>({...e,name:`${s(e.prefix)}${s(e.first_name)} ${s(e.last_name)}`}));
  const ready=settings.credentialConfigured&&settings.serverLiveEnabled&&settings.enabled&&settings.mode==='LIVE';
  const messages:Record<string,string>={ACCEPTED:'MOPH รับคำขอแล้ว — เปิด LINE หมอพร้อมของผู้รับเพื่อตรวจว่าข้อความเข้าแล้ว',FAILED:'MOPH ปฏิเสธคำขอส่งทดสอบ',UNKNOWN:'ยังยืนยันผลไม่ได้ — ตรวจ LINE ของผู้รับก่อนทดสอบใหม่ ระบบไม่ส่งซ้ำอัตโนมัติ',BLOCKED:'ยังไม่ได้ส่ง — ตรวจการตั้งค่าด้านล่าง',SENDING:'คำขอนี้กำลังส่ง กดตรวจผลคำขอเดิมได้โดยไม่ส่งซ้ำ'};
  return <section className="surface padded" aria-label="ทดสอบแจ้งเตือน"><h3>ทดสอบแจ้งเตือนเข้า LINE หมอพร้อม</h3><p className="helper">เลือกผู้รับแล้วกดส่งข้อความทดสอบจริงได้ทันที ไม่ต้องมีนัดหรือรอ worker</p><blockquote className="notice">{TEST_NOTIFICATION_TEXT}</blockquote>{!ready&&<p className="helper">ก่อนทดสอบ: ตั้ง Client_ID/Secret และ MOPH_LIVE_ENABLED=true ฝั่งเว็บ แล้วเปิดการแจ้งเตือนโหมด LIVE ด้านบน</p>}{!recipients.length&&<p className="helper">ยังไม่มีผู้รับที่พร้อม ไปที่ บุคลากร → ผู้รับแจ้งเตือน เพื่อบันทึกเลขบัตรประชาชนและเปิดรับแจ้งเตือนก่อน</p>}<form onSubmit={async e=>{e.preventDefault();const key=requestId||crypto.randomUUID();setRequestId(key);setBusy(true);setError('');try{setResult(await api('notifications/test','POST',{employeeId:Number(employee),requestId:key}) as Result);}catch(e){setError(e instanceof Error?e.message:'ตรวจผลไม่ได้ กดอีกครั้งเพื่อตรวจคำขอเดิม');}finally{setBusy(false);}}}><div className="actions"><Select label="ผู้รับข้อความทดสอบ" options={recipients} value={employee} onChange={e=>{setEmployee(e.target.value);setRequestId('');setResult(undefined);setError('');}} required disabled={busy}/><button className="primary" disabled={busy||!employee||!!result&&result.status!=='SENDING'}>{busy?'กำลังส่ง / ตรวจผล…':requestId?'ตรวจผลคำขอเดิม':'ส่งข้อความทดสอบ'}</button>{result&&result.status!=='SENDING'&&<button type="button" onClick={()=>{setRequestId('');setResult(undefined);setError('');}}>เริ่มการทดสอบใหม่</button>}</div></form>{result&&<p className="helper">HTTP {result.http_status??'—'} · MOPH {result.provider_code??'—'}<br/>รหัสคำขอ: {result.id}</p>}{result&&<p role="status" className={result.status==='ACCEPTED'?'success':'notice'}>{messages[result.status]}{result.safe_error&&<span> · {result.safe_error}</span>}</p>}{error&&<p role="alert" className="error">{error}</p>}</section>;
}
