'use client';
import { useState } from 'react';
import { Plus } from 'lucide-react';
import { PersonnelImport } from './personnel-import';
import { Field,Select,Checks,Table,FormPanel,s,n,thaiDate,ids,type Item,type Api } from './ui';
import type { Masters } from './schedule';
const masterNames:Record<string,string>={departments:'หน่วยงาน',positions:'ตำแหน่ง',levels:'ระดับตำแหน่ง',employmentTypes:'ประเภทการจ้าง',groups:'กลุ่มบริการ',services:'รายการตรวจ'};
export function Registry({tab,masters,employees,members,year,api,reload,canManage,users}:{tab:string;masters:Masters;employees:Item[];members:Item[];year?:Item;api:Api;reload:()=>void;canManage:boolean;users:Item[]}){
 const [form,setForm]=useState<string>(),[item,setItem]=useState<Item>(),[kind,setKind]=useState('departments'),[search,setSearch]=useState('');
 const open=(name:string,value?:Item)=>{setItem(value);setForm(name);};
 const close=()=>{setForm(undefined);setItem(undefined);};
 const save=async(path:string,method:string,body:unknown)=>{await api(path,method,body);reload();};
 const plans=(masters.plans??[]).filter(p=>n(p.fiscal_year_id)===year?.id);
 const titles:Record<string,string>={personnel:'ทะเบียนบุคลากร',roster:'ผู้มีสิทธิ์ตรวจประจำปี',settings:'ข้อมูลตั้งต้น',users:'บัญชีผู้ใช้งาน'};
 return <><div className="section-head"><div><h2>{titles[tab]}</h2><p className="muted">{tab==='roster'?`ทะเบียนและรายการที่ต้องตรวจ ปีงบประมาณ ${s(year?.fiscal_year)}`:'ข้อมูลสำหรับวางแผนและจัดการนัดตรวจ'}</p></div>{canManage&&<button className="primary" onClick={()=>open(tab==='personnel'?'employee':tab==='roster'?'enroll':tab==='users'?'user':'master')}><Plus size={18}/>เพิ่ม{tab==='personnel'?'บุคลากร':tab==='roster'?'ผู้มีสิทธิ์':tab==='users'?'บัญชี':masterNames[kind]}</button>}</div>
 {tab==='personnel'&&canManage&&<div className="notice"><strong>มีข้อมูลบุคลากรอยู่แล้ว?</strong><p>โหลดรายชื่อ หน่วยงาน กลุ่มงาน และตำแหน่งจากไฟล์ที่เตรียมไว้ได้ทั้งชุด</p><button onClick={()=>open('personnelImport')}>นำเข้าบุคลากรทั้งชุด</button></div>}
 {form==='personnelImport'&&<PersonnelImport api={api} reload={reload} onClose={close}/>}
 {form==='master'&&<FormPanel title={`${item?'แก้ไข':'เพิ่ม'}${masterNames[kind]}`} onClose={close} onSubmit={f=>save(`masters/${kind}${item?`/${item.id}`:''}`,item?'PATCH':'POST',{code:f.get('code'),name:f.get('name'),active:f.get('active')==='on',version:item?.version,parentId:n(f.get('parentId'))||null,...(kind==='services'?{groupId:n(item?.service_group_id??f.get('groupId'))}:{})})}><Field label="รหัส (อังกฤษ ตัวเลข _ -)" name="code" defaultValue={s(item?.code)} pattern="[A-Za-z0-9_-]+" maxLength={40} required readOnly={!!item}/><Field label="ชื่อ" name="name" defaultValue={s(item?.name)} required/>{kind==='departments'&&<Select label="หน่วยงานแม่ (ถ้ามี)" name="parentId" options={(masters.departments??[]).filter(d=>d.id!==item?.id)} defaultValue={s(item?.parent_id)}/>} {kind==='services'&&<Select label="กลุ่มบริการ" name="groupId" options={masters.groups??[]} defaultValue={s(item?.service_group_id)} disabled={!!item} required/>}<label className="checkbox"><input type="checkbox" name="active" defaultChecked={!item||!!item.active}/>เปิดใช้งาน</label></FormPanel>}
 {form==='year'&&<FormPanel title="เพิ่มปีงบประมาณ" onClose={close} onSubmit={f=>save('years','POST',{year:n(f.get('year'))})}><Field label="ปีงบประมาณ พ.ศ." name="year" type="number" min={2500} max={2800} defaultValue={2570} required/><p className="helper">ระบบกำหนดช่วง 1 ต.ค. ปีก่อนหน้า ถึง 30 ก.ย. ของปีที่เลือกให้อัตโนมัติ</p></FormPanel>}
 {form==='yearStatus'&&item&&<FormPanel title="เปลี่ยนสถานะปีงบประมาณ" onClose={close} onSubmit={f=>save(`years/${item.id}`,'PATCH',{status:item.status==='OPEN'?'CLOSED':'OPEN',version:item.version,reason:f.get('reason')})}><p>ยืนยัน{item.status==='OPEN'?'ปิด':'เปิด'}ปี {s(item.fiscal_year)} การปิดปีจะระงับการแก้ไขนัดและทะเบียน</p><Field label="เหตุผล" name="reason" required/></FormPanel>}
 {form==='plan'&&year&&<FormPanel title="เพิ่มแผนการตรวจ" onClose={close} onSubmit={f=>save('plans','POST',{yearId:year.id,code:f.get('code'),name:f.get('name'),location:f.get('location'),start:f.get('start'),end:f.get('end'),serviceIds:ids(f)})}><Field label="รหัสแผน" name="code" pattern="[A-Za-z0-9_-]+" required/><Field label="ชื่อแผน" name="name" required/><Field label="สถานที่" name="location" required/><Field label="เริ่มแผน" name="start" type="date" defaultValue={s(year.start_date)} required/><Field label="สิ้นสุดแผน" name="end" type="date" defaultValue={s(year.end_date)} required/><Checks label="รายการตรวจที่เปิดในแผน" options={masters.services??[]}/></FormPanel>}
  {form==='planEdit'&&item&&<FormPanel title="แก้ไขแผนการตรวจ" onClose={close} onSubmit={f=>save(`plans/${item.id}`,'PATCH',{name:f.get('name'),location:f.get('location'),start:f.get('start'),end:f.get('end'),status:f.get('status'),version:item.version,reason:f.get('reason')})}><Field label="ชื่อแผน" name="name" defaultValue={s(item.name)} required/><Field label="สถานที่เริ่มต้น" name="location" defaultValue={s(item.location)} required/><Field label="เริ่มแผน" name="start" type="date" defaultValue={s(item.start_date)} required/><Field label="สิ้นสุดแผน" name="end" type="date" defaultValue={s(item.end_date)} required/><label>สถานะ<select name="status" defaultValue={s(item.status)}><option value="OPEN">เปิดใช้งาน</option><option value="CLOSED">ปิดแผน</option></select></label><Field label="เหตุผลที่แก้ไข" name="reason" required/><p className="helper span-all">การเปลี่ยนสถานที่เริ่มต้นไม่แก้สถานที่ในนัดที่บันทึกไปแล้ว</p></FormPanel>}
 {form==='employee'&&<FormPanel title={item?'แก้ไขบุคลากร / ย้ายหน่วยงาน':'เพิ่มบุคลากร'} onClose={close} onSubmit={f=>save(item?`employees/${item.id}`:'employees',item?'PATCH':'POST',{employeeCode:f.get('employeeCode'),prefix:f.get('prefix'),firstName:f.get('firstName'),lastName:f.get('lastName'),departmentId:n(f.get('departmentId')),positionId:n(f.get('positionId')),levelId:n(f.get('levelId'))||null,employmentTypeId:n(f.get('employmentTypeId'))||null,validFrom:f.get('validFrom'),...(item?{version:item.version,active:f.get('active')==='on'}:{})})}><Field label="รหัสบุคลากร" name="employeeCode" defaultValue={s(item?.employee_code)} readOnly={!!item} pattern="[A-Za-z0-9_-]+" maxLength={40} required/><Field label="คำนำหน้า" name="prefix" defaultValue={s(item?.prefix)} maxLength={30}/><Field label="ชื่อ" name="firstName" defaultValue={s(item?.first_name)} maxLength={100} required/><Field label="นามสกุล" name="lastName" defaultValue={s(item?.last_name)} maxLength={100} required/><Select label="หน่วยงาน" name="departmentId" options={masters.departments??[]} defaultValue={s(item?.department_id)} required/><Select label="ตำแหน่ง" name="positionId" options={masters.positions??[]} defaultValue={s(item?.position_id)} required/><Select label="ระดับตำแหน่ง" name="levelId" options={masters.levels??[]} defaultValue={s(item?.level_id)}/><Select label="ประเภทการจ้าง" name="employmentTypeId" options={masters.employmentTypes??[]} defaultValue={s(item?.employment_type_id)}/><Field label="วันที่เริ่มงาน / วันที่ย้ายมีผล" name="validFrom" type="date" defaultValue={s(item?.valid_from??year?.start_date)} required/>{item&&<label className="checkbox"><input type="checkbox" name="active" defaultChecked={!!item.active}/>ยังปฏิบัติงาน</label>}<p className="span-all helper">เมื่อย้ายหน่วยงาน ระบบเก็บประวัติเดิมไว้ และคงข้อมูลทะเบียนของปีที่จัดทำแล้ว</p></FormPanel>}
 {form==='recipient'&&item&&<FormPanel title={`ผู้รับแจ้งเตือน · ${s(item.first_name)} ${s(item.last_name)}`} onClose={close} onSubmit={f=>save(`employees/${item.id}/recipient`,'PATCH',{cid:s(f.get('cid'))||undefined,enabled:f.get('enabled')==='on',verified:f.get('verified')==='on'})}><Field label={item.has_cid?'เลขบัตรใหม่ (เว้นว่างเพื่อใช้เลขเดิม)':'เลขบัตรประชาชนผู้รับ'} name="cid" type="password" inputMode="numeric" pattern="[0-9]{13}" autoComplete="off"/><label className="checkbox"><input type="checkbox" name="verified"/>ตรวจสอบเลขผู้รับกับเจ้าของข้อมูลแล้ว</label><label className="checkbox"><input type="checkbox" name="enabled" defaultChecked={!!item.notification_enabled}/>เปิดรับการแจ้งเตือน</label><p className="helper">บันทึกแบบเข้ารหัส และไม่แสดงเลขเดิมบนหน้าจอ ผู้รับต้องเชื่อมบริการ MOPH Alert ตามคู่มือโรงพยาบาล</p></FormPanel>}
 {form==='enroll'&&year&&<Enrollment employees={employees} plans={plans} masters={masters} year={year} onClose={close} save={save}/>}
 {form==='user'&&<FormPanel title="เพิ่มบัญชีผู้ใช้" onClose={close} onSubmit={f=>save('users','POST',{username:f.get('username'),displayName:f.get('displayName'),password:f.get('password'),role:f.get('role'),departmentIds:ids(f,'departmentIds')})}><Field label="ชื่อผู้ใช้" name="username" pattern="[A-Za-z0-9_.-]{3,100}" autoComplete="off" required/><Field label="ชื่อที่แสดง" name="displayName" required/><Field label="รหัสผ่าน (อย่างน้อย 12 ตัว)" name="password" type="password" minLength={12} autoComplete="new-password" required/><label>บทบาท<select name="role"><option value="STAFF">เจ้าหน้าที่ · จัดการนัดในหน่วยงาน</option><option value="VIEWER">ผู้ดูรายงาน · เฉพาะภาพรวม</option><option value="ADMIN">ผู้ดูแลระบบ · ทุกหน่วยงาน</option></select></label><Checks label="หน่วยงานที่มีสิทธิ์ (สำหรับเจ้าหน้าที่และผู้ดูรายงาน)" name="departmentIds" options={masters.departments??[]}/></FormPanel>}
 {form==='userStatus'&&item&&<FormPanel title="สถานะบัญชี" onClose={close} onSubmit={()=>save(`users/${item.id}`,'PATCH',{active:!item.active})}><p>ยืนยัน{item.active?'ระงับ':'เปิด'}บัญชี {s(item.username)}</p></FormPanel>}
 {tab==='personnel'&&<div className="surface"><div className="filters"><Field label="ค้นหาบุคลากร" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ชื่อ รหัส หรือหน่วยงาน"/></div><Table headers={['รหัส / ชื่อ–นามสกุล','กลุ่มงาน / หน่วยงาน','ตำแหน่ง','สถานะ','จัดการ']} empty={!employees.length}>{employees.filter(e=>`${e.employee_code} ${e.first_name} ${e.last_name} ${e.department_name}`.includes(search)).map(e=><tr key={e.id}><td><strong>{s(e.prefix)}{s(e.first_name)} {s(e.last_name)}</strong><small>{s(e.employee_code)}</small></td><td><strong>{s(e.group_name)||"—"}</strong><small>{s(e.department_name)}</small></td><td>{s(e.position_name)}</td><td><span className="badge">{e.active?'ปฏิบัติงาน':'พ้นสภาพ'}</span></td><td>{canManage&&<div className="row-actions"><button onClick={()=>open('employee',e)}>แก้ไข</button><button onClick={()=>open('recipient',e)}>ผู้รับแจ้งเตือน</button></div>}</td></tr>)}</Table></div>}
 {tab==='roster'&&<><div className="surface"><Table headers={['บุคลากร','หน่วยงาน / ตำแหน่ง ณ วันที่อ้างอิง','รายการที่ต้องตรวจ']} empty={!members.length}>{members.map(m=><tr key={m.id}><td><strong>{s(m.display_name)}</strong><small>{s(m.employee_code)}</small></td><td>{s(m.department_name)}<small>{s(m.position_name)} · {thaiDate(m.snapshot_date)}</small></td><td>{s(m.requirements).split(',').filter(Boolean).map(r=>{const [p,v,round]=r.split(':');return <span className="requirement" key={r}>{s(masters.services?.find(x=>s(x.id)===v)?.name)} · รอบ {round}<small>{s(plans.find(x=>s(x.id)===p)?.name)}</small></span>;})}</td></tr>)}</Table></div><section className="surface padded"><div className="section-head"><h3>แผนการตรวจปีนี้</h3>{canManage&&<button onClick={()=>open('plan')}>เพิ่มแผนการตรวจ</button>}</div><Table headers={['รหัส','ชื่อแผน','ช่วงวันที่','สถานที่ / สถานะ','จัดการ']} empty={!plans.length}>{plans.map(p=><tr key={p.id}><td>{s(p.code)}</td><td>{s(p.name)}</td><td>{thaiDate(p.start_date)} – {thaiDate(p.end_date)}</td><td>{s(p.location)}<small>{p.status==="OPEN"?"เปิดใช้งาน":"ปิดแผน"}</small></td><td>{canManage&&<button onClick={()=>open("planEdit",p)}>แก้ไขแผน</button>}</td></tr>)}</Table></section></>}
 {tab==='settings'&&<><div className="surface padded"><div className="section-head"><h3>ปีงบประมาณ</h3>{canManage&&<button onClick={()=>open('year')}>เพิ่มปีงบประมาณ</button>}</div><Table headers={['ปีงบประมาณ','ช่วงวันที่','สถานะ','จัดการ']} empty={!masters.years?.length}>{masters.years?.map(y=><tr key={y.id}><td><strong>{s(y.fiscal_year)}</strong></td><td>{thaiDate(y.start_date)} – {thaiDate(y.end_date)}</td><td>{y.status==='OPEN'?'เปิดใช้งาน':'ปิดปีแล้ว'}</td><td>{canManage&&<button onClick={()=>open('yearStatus',y)}>{y.status==='OPEN'?'ปิดปี':'เปิดปีอีกครั้ง'}</button>}</td></tr>)}</Table></div><div className="surface"><div className="subnav">{Object.entries(masterNames).map(([k,v])=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);close();}}>{v}</button>)}</div><Table headers={['รหัส','ชื่อ','สถานะ','จัดการ']} empty={!masters[kind]?.length}>{masters[kind]?.map(m=><tr key={m.id}><td>{s(m.code)}</td><td>{s(m.name)}</td><td>{m.active?'เปิดใช้งาน':'ปิดใช้งาน'}</td><td>{canManage&&<button onClick={()=>open('master',m)}>แก้ไข</button>}</td></tr>)}</Table></div></>}
 {tab==='users'&&<div className="surface"><Table headers={['ชื่อผู้ใช้','ชื่อที่แสดง','บทบาท','สถานะ','จัดการ']} empty={!users.length}>{users.map(u=><tr key={u.id}><td>{s(u.username)}</td><td>{s(u.display_name)}</td><td>{s(u.roles)}</td><td>{u.active?'ใช้งาน':'ระงับ'}</td><td><button onClick={()=>open('userStatus',u)}>{u.active?'ระงับบัญชี':'เปิดบัญชี'}</button></td></tr>)}</Table></div>}
 </>;
}
function Enrollment({employees,plans,masters,year,onClose,save}:{employees:Item[];plans:Item[];masters:Masters;year:Item;onClose:()=>void;save:(path:string,method:string,body:unknown)=>Promise<void>}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const snapshot=today<s(year.start_date)?s(year.start_date):today>s(year.end_date)?s(year.end_date):today;
 const [plan,setPlan]=useState(s(plans[0]?.id)),[all,setAll]=useState(true);const allowed=s(plans.find(p=>s(p.id)===plan)?.service_ids).split(',').map(Number);
 return <FormPanel title="เพิ่มผู้มีสิทธิ์และรายการตรวจประจำปี" onClose={onClose} onSubmit={f=>save(all?'members/bulk':'members','POST',{...(all?{employeeIds:employees.filter(e=>e.active).map(e=>e.id)}:{employeeId:n(f.get('employeeId'))}),planId:n(plan),snapshotDate:f.get('snapshotDate'),rounds:n(f.get('rounds')),serviceIds:ids(f)})}><label className="checkbox span-all"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>เพิ่มบุคลากรที่เปิดใช้งานทั้งหมด ({employees.filter(e=>e.active).length} คน)</label><Select label="บุคลากร" name="employeeId" disabled={all} options={employees.filter(e=>e.active).map(e=>({...e,name:`${e.employee_code} · ${e.first_name} ${e.last_name}`}))} required/><Select label="แผน" options={plans} value={plan} onChange={e=>setPlan(e.target.value)} required/><Field label="วันที่อ้างอิงตำแหน่งและหน่วยงาน" name="snapshotDate" type="date" defaultValue={snapshot} min={s(year.start_date)} max={s(year.end_date)} required/><Field label="จำนวนรอบที่ต้องตรวจ" name="rounds" type="number" defaultValue={1} min={1} max={10} required/><Checks key={plan} label="รายการที่ต้องตรวจ" options={(masters.services??[]).filter(v=>allowed.includes(v.id))}/><p className="helper span-all">เพิ่มทะเบียนเดิมซ้ำได้เพื่อเติมรายการที่ต้องตรวจ โดยไม่สร้างรายชื่อซ้ำหรือเปลี่ยนข้อมูลอ้างอิงเดิม</p></FormPanel>;
}
