'use client';
import { AnnualPlan,serviceTone } from './annual-plan';
import { useState } from 'react';
import { Plus,Download,ChevronLeft,ChevronRight,CalendarDays,List } from 'lucide-react';
import { Field,Select,Checks,Table,FormPanel,s,n,thaiDate,ids,type Item,type Api } from './ui';
import { statusLabels } from '@/src/domain/validation';
export type Masters=Record<string,Item[]>;
export type Filters=Record<string,string>;
export const labels=statusLabels as Record<string,string>;
export function FiltersBar({masters,filters,setFilters}:{masters:Masters;filters:Filters;setFilters:(f:Filters)=>void}){const change=(key:string,value:string)=>setFilters({...filters,[key]:value,page:'1'});return <div className="filters"><Field label="ค้นหาบุคลากร" placeholder="ชื่อ หรือรหัสบุคลากร" value={filters.q??''} onChange={e=>change('q',e.target.value)}/><Select label="หน่วยงาน" options={masters.departments??[]} value={filters.department??''} onChange={e=>change('department',e.target.value)}/><Select label="กลุ่มบริการ" options={masters.groups??[]} value={filters.group??''} onChange={e=>change('group',e.target.value)}/><label>สถานะ<select value={filters.status??''} onChange={e=>change('status',e.target.value)}><option value="">ทุกสถานะ</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><details><summary>ตัวกรองเพิ่มเติม</summary><div className="filter-extra"><Field label="ตั้งแต่วันที่" type="date" value={filters.from??''} onChange={e=>change('from',e.target.value)}/><Field label="ถึงวันที่" type="date" value={filters.to??''} onChange={e=>change('to',e.target.value)}/><Select label="รายการตรวจ" options={masters.services??[]} value={filters.service??''} onChange={e=>change('service',e.target.value)}/><button onClick={()=>setFilters({})}>ล้างตัวกรอง</button></div></details></div>;}
export function Schedule({data,total,calendar,masters,members,year,api,reload,permissions,filters,setFilters,query}:{data:Item[];total:number;calendar:Item[];masters:Masters;members:Item[];year:Item;api:Api;reload:()=>void;permissions:string[];filters:Filters;setFilters:(f:Filters)=>void;query:string}){
 const [mode,setMode]=useState('list'),[editing,setEditing]=useState<Item|null|undefined>(),[status,setStatus]=useState<Item>(),[month,setMonth]=useState(s(year.start_date).slice(0,7));
 const can=(p:string)=>permissions.includes(p),page=n(filters.page)||1;
 const plans=(masters.plans??[]).filter(p=>n(p.fiscal_year_id)===year.id);
 const shift=(v:number)=>{const d=new Date(`${month}-15T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+v);setMonth(d.toISOString().slice(0,7));};
 const first=new Date(`${month}-01T00:00:00Z`),offset=(first.getUTCDay()+6)%7,days=new Date(first.getUTCFullYear(),first.getUTCMonth()+1,0).getDate();
 return <><div className="section-head"><div><h2>ตารางนัดตรวจสุขภาพ</h2><p className="muted">{total.toLocaleString('th-TH')} นัดหมาย · ปีงบประมาณ {s(year.fiscal_year)}</p></div><div className="actions">{can('export.execute')&&<a className="button" href={`/api/v1/exports/appointments?${query}`}><Download size={16}/>ส่งออก Excel</a>}{can('appointment.write')&&<button className="primary" onClick={()=>setEditing(null)}><Plus size={18}/>เพิ่มนัดหมาย</button>}</div></div>
 {editing!==undefined&&<AppointmentForm key={editing?.id??'new'} item={editing} members={members} masters={masters} plans={plans} api={api} onClose={()=>setEditing(undefined)} reload={reload}/>}
 {status&&<FormPanel title={`บันทึกสถานะ · ${s(status.display_name)}`} onClose={()=>setStatus(undefined)} onSubmit={async f=>{await api(`appointments/${status.id}/status`,'PATCH',{status:f.get('status'),version:status.version,reason:f.get('reason')});reload();}}><label>สถานะใหม่<select name="status" required>{(status.status==='SCHEDULED'?['CHECKED_IN','NO_SHOW','CANCELLED']:status.status==='CHECKED_IN'?['COMPLETED','CANCELLED']:['CHECKED_IN']).map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><Field label="เหตุผล / หมายเหตุ" name="reason" required maxLength={500}/><p className="span-all helper">การเลือก “ตรวจแล้ว” ยืนยันว่ารับบริการครบทุกรายการในนัดนี้ กรุณาตรวจสอบก่อนบันทึก</p></FormPanel>}
 <div className="surface"><FiltersBar masters={masters} filters={filters} setFilters={setFilters}/><div className="table-toolbar"><div className="segmented"><button aria-pressed={mode==='list'} onClick={()=>setMode('list')}><List size={16}/>รายการนัด</button><button aria-pressed={mode==='calendar'} onClick={()=>setMode('calendar')}><CalendarDays size={16}/>ปฏิทิน</button></div><span className="muted small">เวลาประเทศไทย · พ.ศ.</span></div>
 {mode==='list'?<><Table headers={['บุคลากร / หน่วยงาน','วัน–เวลานัด','บริการ / รอบ','สถานะ','จัดการ']} empty={!data.length}>{data.map(a=><tr key={a.id}><td><strong>{s(a.display_name)}</strong><small>{s(a.employee_code)} · {s(a.department_name)}</small></td><td>{thaiDate(a.appointment_date)}<small>{s(a.appointment_time).slice(0,5)} น. · {s(a.location)}</small></td><td><strong>{s(a.group_name)} · รอบ {s(a.round_no)}</strong><small>{s(a.services)}{n(a.attempt_no)>1?` · นัดทดแทน ${a.attempt_no}`:''}</small></td><td><span className={`badge ${s(a.status).toLowerCase()}`}>{labels[s(a.status)]}</span></td><td><div className="row-actions">{can('appointment.write')&&a.status==='SCHEDULED'&&<button onClick={()=>setEditing(a)}>แก้ไข</button>}{can('attendance.write')&&['SCHEDULED','CHECKED_IN','NO_SHOW'].includes(s(a.status))&&<button onClick={()=>setStatus(a)}>สถานะ</button>}</div></td></tr>)}</Table><div className="pagination"><span>{total?`${(page-1)*50+1}–${Math.min(page*50,total)} จาก ${total}`:'ยังไม่มีนัดหมาย'}</span><div className="actions"><button disabled={page===1} onClick={()=>setFilters({...filters,page:String(page-1)})}>ก่อนหน้า</button><button disabled={page*50>=total} onClick={()=>setFilters({...filters,page:String(page+1)})}>ถัดไป</button></div></div></>:<><div className="month-nav"><button aria-label="เดือนก่อน" disabled={month<=s(year.start_date).slice(0,7)} onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><h3>{new Intl.DateTimeFormat('th-TH',{month:'long',year:'numeric',timeZone:'UTC'}).format(first)}</h3><button aria-label="เดือนถัดไป" disabled={month>=s(year.end_date).slice(0,7)} onClick={()=>shift(1)}><ChevronRight size={18}/></button></div><div className="calendar-scroll"><div className="calendar">{['จ.','อ.','พ.','พฤ.','ศ.','ส.','อา.'].map(d=><div key={d} className="weekday">{d}</div>)}{Array.from({length:offset},(_,i)=><div key={`blank${i}`} className="day blank"/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,items=calendar.filter(a=>a.appointment_date===date);return <div key={date} className="day"><span>{i+1}</span>{(masters.groups??[]).map((g,index)=>{const count=items.filter(a=>n(a.service_group_id)===g.id).length;return count?<button className={`calendar-chip ${serviceTone(s(g.name),index)}`} key={g.id} onClick={()=>{setFilters({...filters,from:date,to:date,group:String(g.id),page:'1'});setMode('list');}}>{s(g.name)}<b>{count}</b></button>:null;})}</div>;})}</div></div></>}
 </div></>;
}
function AppointmentForm({item,members,masters,plans,api,onClose,reload}:{item:Item|null;members:Item[];masters:Masters;plans:Item[];api:Api;onClose:()=>void;reload:()=>void}){
 const [plan,setPlan]=useState(s(item?.plan_id??plans[0]?.id)),[group,setGroup]=useState(s(item?.service_group_id??masters.groups?.[0]?.id));
 const chosen=plans.find(p=>s(p.id)===plan),allowed=s(chosen?.service_ids).split(',').map(Number);
 return <FormPanel title={item?'แก้ไขนัดหมาย':'เพิ่มนัดหมาย'} onClose={onClose} onSubmit={async f=>{await api(item?`appointments/${item.id}`:'appointments',item?'PATCH':'POST',{memberId:n(item?.member_id??f.get('memberId')),planId:n(item?.plan_id??f.get('planId')),groupId:n(item?.service_group_id??f.get('groupId')),roundNo:n(item?.round_no??f.get('roundNo')),attemptNo:n(item?.attempt_no??f.get('attemptNo')),date:f.get('date'),time:f.get('time'),location:f.get('location'),queueLabel:f.get('queueLabel'),note:f.get('note'),serviceIds:ids(f),...(item?{version:item.version,reason:f.get('reason')}:{})});reload();}}>
 <Select label="บุคลากรในทะเบียนปีนี้" name="memberId" options={members} display="display_name" defaultValue={s(item?.member_id)} required disabled={!!item}/><AnnualPlan name="planId" plans={plans} value={plan} onChange={setPlan} disabled={!!item}/><Select label="กลุ่มบริการ" name="groupId" options={masters.groups??[]} value={group} onChange={e=>setGroup(e.target.value)} required disabled={!!item}/><Field label="รอบที่" name="roundNo" type="number" min={1} max={10} defaultValue={n(item?.round_no)||1} required disabled={!!item}/><Field label="ครั้งนัด (ทดแทนเมื่อขาด/ยกเลิก)" name="attemptNo" type="number" min={1} max={20} defaultValue={n(item?.attempt_no)||1} required disabled={!!item}/><Field label="วันที่นัด" name="date" type="date" defaultValue={s(item?.appointment_date??chosen?.start_date)} min={s(chosen?.start_date)} max={s(chosen?.end_date)} required/><Field label="เวลานัด" name="time" type="time" defaultValue={s(item?.appointment_time).slice(0,5)||'08:30'} required/><Field label="สถานที่" name="location" defaultValue={s(item?.location??chosen?.location)} required maxLength={200}/><Field label="คิว / ช่วงเวลา" name="queueLabel" defaultValue={s(item?.queue_label)} maxLength={100}/><Field label="หมายเหตุ" name="note" defaultValue={s(item?.note)} maxLength={1000}/><Checks key={`${plan}-${group}`} label="รายการตรวจ (ต้องอยู่ในสิทธิ์ของบุคลากรและรอบนี้)" options={(masters.services??[]).filter(v=>n(v.service_group_id)===n(group)&&allowed.includes(v.id))} selected={s(item?.service_ids).split(',').map(Number)}/>{item&&<Field label="เหตุผลที่แก้ไข" name="reason" required maxLength={500}/>}
 </FormPanel>;
}
