CREATE TABLE hr_personnel (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 cid_hmac CHAR(64) CHARACTER SET ascii NOT NULL UNIQUE,
 name_key VARCHAR(255) NOT NULL,
 prefix VARCHAR(50) NOT NULL DEFAULT '',
 first_name VARCHAR(100) NOT NULL,
 last_name VARCHAR(100) NOT NULL,
 position VARCHAR(255) NOT NULL DEFAULT '',
 department VARCHAR(255) NOT NULL DEFAULT '',
 work_group VARCHAR(255) NOT NULL DEFAULT '',
 mission_group VARCHAR(255) NOT NULL DEFAULT '',
 status VARCHAR(100) NOT NULL DEFAULT '',
 imported_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 INDEX(name_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
